server:
  port: 80
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1632938020@qq.com #邮箱
    password: ********* #客户端授权码
    protocol: smtp #发送邮件协议
    properties:
      mail:
        smtp:
          port: 465
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
